version: '3.8'

services:
  frontend:
    image: frontend-image
    ports:
      - "8080:80"
    networks:
      - app-network

  backend:
    image: backend-image
    ports:
      - "8082:8082"
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: db_pass123
    ports:
      - "3306:3306"
    networks:
      - app-network

  results-frontend:
    image: results-frontend-image
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
