version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    networks:
      - default

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: votes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  results-frontend:
    build:
      context: ./results-frontend
    ports:
      - "8081:8080"
    networks:
      - default

networks:
  default:
    driver: bridge
